### ISSUE TITLE
Como usuario de la aplicación Muebles Blanca, requiero que la aplicación me permita crear mi usuario por medio de un formulario 

### ISSUE THREAD

**Issue by derlyduarteIT** [Fgarciaro123/MueblesBlancaAdministracion#1]
Como usuario de la aplicación   Muebles blanca, requiero que la aplicación de escritorio me permita crear mi usuario por medio de un formulario, donde el formulario a diligenciar debe contener los siguientes campos:

- Nombres y apellidos, el cual debe ser obligatorio su diligencia miento; este campo debe ser de tipo texto.

-Tipo de documento ej: Número de cédula, el cual debe ser obligatorio su diligencia miento; este campo debe ser de tipo texto.

- Contraseña (este campo debe permitir que se visualice de forma encriptada )

- Rol

El usuario creado debe quedar con estado Activo cuando :  

- El usuario se haya registrado satisfactoriamente 

Requerimiento asociado:
Requerimiento asociado USUARIO-1--->Crear usuario

**Comment by Fgarciaro123** [comment]
Se crea funcionalidad de creación de administrador, la cual solo estará disponible la primera vez que se ejecuta el sistema, pendiente validar requerimiento de cambio de password 

Por favor actualizar, base de datos y proyecto para validar funcionalidad
