### ISSUE TITLE
Inquietud : Para que me sirve el botón cancelar? en login

### ISSUE THREAD

**Issue by derlyduarteIT** [Fgarciaro123/MueblesBlancaAdministracion#10]
Hago clic en el botón cancelar

![image](https://user-images.githubusercontent.com/37149973/57994249-e736aa00-7a81-11e9-935c-3c0905c8e30a.png)
y me lleva a esto
![image](https://user-images.githubusercontent.com/37149973/57994270-fc133d80-7a81-11e9-859e-36b4a0d188ed.png)

**Comment by Fgarciaro123** [comment]
Para Salir del sistema, y cerrar el programa
