### ISSUE TITLE
Bug: No me permite crear producto 

### ISSUE THREAD

**Issue by derlyduarteIT** [Fgarciaro123/MueblesBlancaAdministracion#11]
Se realiza la prueba de creación de producto
![image](https://user-images.githubusercontent.com/37149973/57994460-da668600-7a82-11e9-84a6-492c9595e2e7.png)

Me muestra el siguiente mensaje 
![image](https://user-images.githubusercontent.com/37149973/57994466-ee11ec80-7a82-11e9-9956-0b6e498fea91.png)

**Comment by Fgarciaro123** [comment]
El error se presenta porque no se lleno el campo ancho validar nuevamente
