### ISSUE TITLE
IMÁGENES MÓDULOS

### ISSUE THREAD

**Issue by derlyduarteIT** [Fgarciaro123/MueblesBlancaAdministracion#14]
Roles
![image](https://user-images.githubusercontent.com/37149973/57995090-cc663480-7a85-11e9-8a9c-9fe1ac6e0728.png)

Productos

![image](https://user-images.githubusercontent.com/37149973/57995184-51e9e480-7a86-11e9-99fd-4bab5eaabe3e.png)
Tipos de documento
![image](https://user-images.githubusercontent.com/37149973/57995449-bbb6be00-7a87-11e9-8dab-1c41609e5b4f.png)
o algo asi
![image](https://user-images.githubusercontent.com/37149973/57995471-e43eb800-7a87-11e9-8ead-8c7bf85d7ec5.png)

Categorías 
![image](https://user-images.githubusercontent.com/37149973/57995537-3aabf680-7a88-11e9-90c9-b730f77c43d8.png)

**Comment by Fgarciaro123** [comment]
Son imagenes muy grandes no se acomodan, sugiero buscar iconos

**Comment by Fgarciaro123** [comment]
se actualiza
