### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by derlyduarteIT** [Fgarciaro123/MueblesBlancaAdministracion#16]
se realiza la siguiente prueba selecciono el botón de gestionar imágenes
![image](https://user-images.githubusercontent.com/37149973/58001272-aa2de000-7aa0-11e9-902a-3549e61006a7.png)
 clic en cargar imagen 
![image](https://user-images.githubusercontent.com/37149973/58001317-bfa30a00-7aa0-11e9-8ab6-85dfa326cbaf.png)
Dejo en blanco y selecciono guardar
**Error 1**
![image](https://user-images.githubusercontent.com/37149973/58001347-ce89bc80-7aa0-11e9-80e7-02dbaa82799d.png)
paso 2 de ejecución de pruebas
selecciono examinar
![image](https://user-images.githubusercontent.com/37149973/58001502-43f58d00-7aa1-11e9-9976-6cf9d97cc111.png)
inserto imagen 
![image](https://user-images.githubusercontent.com/37149973/58001535-5b347a80-7aa1-11e9-8256-67769a22f7da.png)

 clic en guardar
![image](https://user-images.githubusercontent.com/37149973/58001564-71dad180-7aa1-11e9-92ad-8beedd865e84.png)
OK
3 Prueba 
![image](https://user-images.githubusercontent.com/37149973/58001615-99319e80-7aa1-11e9-86a9-34552fa84b76.png)
OK

Pero al hacer clic de nuevo me envía aqui: 
![image](https://user-images.githubusercontent.com/37149973/58001365-dfd2c900-7aa0-11e9-9e2a-cb7ecb55a324.png)

![image](https://user-images.githubusercontent.com/37149973/58001137-41defe80-7aa0-11e9-8e12-072634972a02.png)

**Comment by Fgarciaro123** [comment]
se corrige bug
