### ISSUE TITLE
Mejora: En la  interfaz se podría ajustar el tamaño y colocar una imagen de la empresa O bueno un logo al iniciar

### ISSUE THREAD

**Issue by derlyduarteIT** [Fgarciaro123/MueblesBlancaAdministracion#2]
Login que se tiene
![image](https://user-images.githubusercontent.com/37149973/57777072-953efe80-76e6-11e9-8e51-9f24902803af.png)

Login que se puede cambiar 

![image](https://user-images.githubusercontent.com/37149973/57778140-097aa180-76e9-11e9-96a8-3b84ad587862.png)

1. Cuando se ingrese y se deje los espacios en blanco se puede cambiar el mensaje ya que no es claro podría ser 
Nombre de usuario o contraseña inválida.

**Comment by Fgarciaro123** [comment]
Se ajusta login, actualizar y validar
