### ISSUE TITLE
Bug: Ortografía 

### ISSUE THREAD

**Issue by derlyduarteIT** [Fgarciaro123/MueblesBlancaAdministracion#3]
**Módulo  de tipos de documento** 
- modulo por Módulo

- codigo por código

- descripcion por descripción 

- fecha creacion por fecha de creación 

- usuario creacion por usuario creación

-   fecha modificacion por fecha modificación

- usuario modificacion por usuario modificación
  
y en los demás módulos

**Comment by Fgarciaro123** [comment]
Se ajusta la información solicitada por favor actualizar y validar

**Comment by derlyduarteIT** [comment]
Se vuelve abrir este error motivos: 
![image](https://user-images.githubusercontent.com/37149973/58000029-1eff1b00-7a9d-11e9-83cd-f317a85aef08.png)
Cambiar 
- menu principal = menú principal
- administracion categorias = administración categorías 
y todas las que dicen administracion por administración
