### ISSUE TITLE
Bug: No me permite crear producto 

### ISSUE THREAD

**Issue by derlyduarteIT** [Fgarciaro123/MueblesBlancaAdministracion#4]
Al realizar la prueba de creación de producto al seleccionar guardar me saca del módulo
 
![image](https://user-images.githubusercontent.com/37149973/57901177-9167c500-7829-11e9-8a8f-1ca36b1c7f7f.png)

![image](https://user-images.githubusercontent.com/37149973/57901119-3fbf3a80-7829-11e9-87ff-22acf1647b8d.png)
Solo me funciona el botón de limpiar del módulo producto ningún otro funciona

**Comment by Fgarciaro123** [comment]
El error se presenta porque el campo garantia se definio como numerico y esa garantia va en meses,

**Comment by Fgarciaro123** [comment]
Se corrige issue, por favor actualizar y validar
