### ISSUE TITLE
Bug: Error al agregar un tipo de documento 

### ISSUE THREAD

**Issue by derlyduarteIT** [Fgarciaro123/MueblesBlancaAdministracion#6]
Se realiza la prueba de agregar tipo de documento
![image](https://user-images.githubusercontent.com/37149973/57993424-79d54a00-7a7e-11e9-8141-dc0991ea6ecc.png)
Ingreso el nombre del tipo de documento
![image](https://user-images.githubusercontent.com/37149973/57993443-97a2af00-7a7e-11e9-8e51-ddd5abc54029.png)
Clic en grabar 
**ERROR**
![image](https://user-images.githubusercontent.com/37149973/57993486-c0c33f80-7a7e-11e9-8fef-b07d27e411c6.png)
Como sugerencia se podría cambiar la palabra grabar por guardar

**Comment by Fgarciaro123** [comment]
Se ajusta titulo de botones y se corrige bug
