### ISSUE TITLE
Bug: El módulo de Roles no me permite editar 

### ISSUE THREAD

**Issue by derlyduarteIT** [Fgarciaro123/MueblesBlancaAdministracion#7]
Se  realiza la prueba de editar  un rol y me sale el siguiente mensaje
![image](https://user-images.githubusercontent.com/37149973/57993796-16e4b280-7a80-11e9-9eda-2d3f3bcd3520.png)
Como sugerencia se puede cambiar de mensaje
![image](https://user-images.githubusercontent.com/37149973/57993897-7fcc2a80-7a80-11e9-8c0b-831e831a87d5.png)
Rol creado exitosamente

**Comment by Fgarciaro123** [comment]
El rol de administrador siempre estara activo, por lo cual no se permite su modificacion,

**Comment by derlyduarteIT** [comment]
No es clara tu respuesta para mi me podrías explicar mejor?
La prueba fue:
ingrese un rol de ciente
y clic en grabar 
al editar y escribir bien la palabra cliente no me permitio
