### ISSUE TITLE
Bug: En el módulo de Rol No me permite eliminar un rol

### ISSUE THREAD

**Issue by derlyduarteIT** [Fgarciaro123/MueblesBlancaAdministracion#8]
Se realiza la prueba de eliminar un rol y me muestra el mensaje
![image](https://user-images.githubusercontent.com/37149973/57994082-1dbff500-7a81-11e9-8802-8a78f1854292.png)

**Comment by Fgarciaro123** [comment]
El rol administrador siempre estara activo no se permite su eliminacion
