### ISSUE TITLE
Bug: Al eliminar un tipo de documentoS

### ISSUE THREAD

**Issue by derlyduarteIT** [Fgarciaro123/MueblesBlancaAdministracion#9]
Se realiza la prueba de eliminar un tipo de documento y me sale este error
![image](https://user-images.githubusercontent.com/37149973/57994189-8effa800-7a81-11e9-8817-2d2740833fe5.png)

**Comment by Fgarciaro123** [comment]
El error se presenta por integridad de datos, no se permite la eliminacion porque existe informacion de tablas atados a esta parametria, se realiza validacion del error y se muestra mensaje a usuario
